[package]
name = "eth-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
alloy = { version = "0.3", features = ["full"] }
tokio = { version = "1.41.1", features = ["full"] }
eyre = "0.6.12"
reqwest = "0.12.9"